name: SkyBackpack
version: 1.0-SNAPSHOT
main: skyBackpack.SkyBackpack
api-version: '1.21'
author: elockexe
description: Backpack GUI system with upgrades via /upgrade

commands:
  upgrade:
    description: Upgrade ton backpack au niveau suivant
    usage: /upgrade
    permission: skybackpack.upgrade
    permission-message: "§cTu n'as pas la permission d'utiliser cette commande."

permissions:
  skybackpack.upgrade:
    description: Permet d'utiliser /upgrade
    default: true
